Feat: Create workflow to RequestOutFitWindowPacket.
OpenCoreMMO/OpenCoreMMO pull request #324
Opened 2022-07-21 02:53 UTC by Lowpoc

Previews:
![image](https://user-images.githubusercontent.com/17841549/180120714-1f3d489e-2cc8-40f2-bf12-51c10f4b7919.png)
![image](https://user-images.githubusercontent.com/17841549/180120745-552a2f1b-fb3a-4239-aba6-cad9ecd7982b.png)
![image](https://user-images.githubusercontent.com/17841549/180120773-4938773a-de91-4566-a438-d1d981cc01d7.png)
![image](https://user-images.githubusercontent.com/17841549/180588471-d93b65b4-a298-41cd-b80c-e29bc6c908d9.png)
![image](https://user-images.githubusercontent.com/17841549/180588491-6c7a0074-2049-4692-81d0-57f7737cada9.png)

2022-07-22 12:31 UTC, caioavidal requested changes

2022-07-22 12:31 UTC, caioavidal commented on src/Data/NeoServer.Data/Seeds/PlayerModelSeed.cs
> -                Gender = Gender.Male,
can you ignore this file changes?

2022-07-22 12:31 UTC, caioavidal commented on src/Game/NeoServer.Game.Common/Creatures/Players/Gender.cs
> +    Male
Can we have a byte assigned to the type?
ie:  Male = 0, Female = 1

2022-07-22 13:23 UTC, MarcusSilvaDev commented on src/Game/NeoServer.Game.Common/Creatures/Players/Gender.cs
> +    Male
It is possible, but currently to the outfit Object, the values are inverted.  We need to find a solution if there are behaviors different from this.

**ie: Female = 0, Male = 1**

2022-07-22 13:57 UTC, caioavidal commented on src/Game/NeoServer.Game.Common/Creatures/Players/Gender.cs
> +    Male
I think we can change it to: Female = 0, Male = 1 then.
this is probably only used by outfits

2022-07-25 21:30 UTC, caioavidal approved these changes

2022-07-25 21:30 UTC, merged